# Generated by Django 4.0.6 on 2023-08-12 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0009_item_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wemes.user'),
        ),
    ]
