# Generated by Django 4.0.6 on 2023-08-12 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0010_alter_transaction_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='category',
        ),
    ]
