# Generated by Django 4.0.6 on 2023-08-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wemes', '0011_rename_type_category_rename_type_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_four',
            field=models.CharField(max_length=4),
        ),
    ]
